FROM php:8.2-apache

# Enable Apache rewrite (important for routing)
RUN a2enmod rewrite

# Install PostgreSQL extensions (needed for Supabase)
RUN docker-php-ext-install pdo pdo_pgsql pgsql

# Copy all project files
COPY . /var/www/html/

# Fix permissions
RUN chown -R www-data:www-data /var/www/html

# Set working directory
WORKDIR /var/www/html

EXPOSE 80